### ISSUE TITLE
提取特征时出现TypeError

### ISSUE THREAD

**Issue by JHB11Hinson** [FlameSky-S/MMSA-FET#41]
config = {
    "audio": {
        "tool": "opensmile",
        "sample_rate": 16000,
        "args": {
            "feature_set": "eGeMAPSv02",
            "feature_level": "LowLevelDescriptors",
            "start": None,
            "end": None,
        }
    },
    "video": {
        "tool": "openface",
        "fps": 10,
        'multiFace': {'enable': False,
                      'device': 'cuda:0',
                      'facedetScale': 0.25,
                      'minTrack': 10,
                      'numFailedDet': 10,
                      'minFaceSize': 1,
                      'cropScale': 0.4},
        "average_over": 1,
        "args": {
            "hogalign": False,
            "simalign": False,
            "nobadaligned": False,
            "landmark_2D": True,
            "landmark_3D": False,
            "pdmparams": False,
            "head_pose": False,
            "action_units": True,
            "gaze": False,
            "tracked": False
        }
    },
    "text": {
        "model": "bert",
        "device": "cpu",
        "pretrained": "bert-base-chinese",
        "args": {}
    }
} 

fet = FeatureExtractionTool(config=config)

infile_path=os.path.abspath('/data/huangjingwang/SCI/MMSA/cut/test_output/output_video_002.mp4')
outfile_path=os.path.abspath('/data/huangjingwang/SCI/MMSA/cut/test_output/feature_get.pkl')
text_path=os.path.abspath("/data/huangjingwang/SCI/MMSA/cut/input.txt")
fet.run_single(in_file=infile_path, out_file=outfile_path,text_file=text_path)

运行后报错：
FET-Single - An Error Occured:
Traceback (most recent call last):
  File "/data/huangjingwang/.conda/envs/hjw_nlp/lib/python3.11/site-packages/MSA_FET/single.py", line 305, in run_single
    text_result, text_tokens = self._text_extract_single(None, text)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/huangjingwang/.conda/envs/hjw_nlp/lib/python3.11/site-packages/MSA_FET/single.py", line 173, in _text_extract_single
    text = self.text_extractor.load_text_from_file(in_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/huangjingwang/.conda/envs/hjw_nlp/lib/python3.11/site-packages/MSA_FET/extractors/baseExtractor.py", line 89, in load_text_from_file
    return open(file, 'r').read().strip()
           ^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/data/huangjingwang/SCI/MMSA/cut/test2.py", line 65, in <module>
    fet.run_single(in_file=infile_path, out_file=outfile_path,text_file=text_path)
  File "/data/huangjingwang/.conda/envs/hjw_nlp/lib/python3.11/site-packages/MSA_FET/single.py", line 341, in run_single
    raise e
  File "/data/huangjingwang/.conda/envs/hjw_nlp/lib/python3.11/site-packages/MSA_FET/single.py", line 305, in run_single
    text_result, text_tokens = self._text_extract_single(None, text)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/huangjingwang/.conda/envs/hjw_nlp/lib/python3.11/site-packages/MSA_FET/single.py", line 173, in _text_extract_single
    text = self.text_extractor.load_text_from_file(in_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/huangjingwang/.conda/envs/hjw_nlp/lib/python3.11/site-packages/MSA_FET/extractors/baseExtractor.py", line 89, in load_text_from_file
    return open(file, 'r').read().strip()
           ^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by JHB11Hinson** [comment]
在使用text字符串代替传入文件后解决
